const productsDB = [
    {
        id: 1,
        name: "9am Dive",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 4,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 2,
        name: "Turathi Electric",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 3,
        name: "9 AM Mujer",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 4,
        name: "9 PM Pour Femme",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 5,
        name: "Aqua Dubai",
        brand: "Al Haramain",
        ml: 75,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 6,
        name: "Aqua Dubai",
        brand: "Al Haramain",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 7,
        name: "Gold Edition",
        brand: "Al Haramain",
        ml: 60,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 8,
        name: "Beach Party",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 9,
        name: "Club de Bling",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 10,
        name: "Club de Nuit Iconic",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 11,
        name: "Club de Nuit Imperiale",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 12,
        name: "Club de Nuit Maleka",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 13,
        name: "Club de Nuit Sillage",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 14,
        name: "Miss Armaf Attitude",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 5,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 15,
        name: "Club de Nuit Untold",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 16,
        name: "Mandarin Sky Elixir",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 17,
        name: "Odyssey Mega",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 18,
        name: "Odyssey Homme Negro",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 19,
        name: "Odyssey Homme White",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 20,
        name: "Odyssey Spectra",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 21,
        name: "Odyssey Artisto",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 22,
        name: "Odyssey Toffee Coffee",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 23,
        name: "Odyssey Eud de Montagne",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 24,
        name: "Rohit",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 25,
        name: "Rome Pour Homme",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 26,
        name: "Rome Extradose",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 27,
        name: "Rome Imagine",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 28,
        name: "Rome Extradose Pour Femme",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 29,
        name: "Rome Paradox",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 30,
        name: "Romen Yum Yum",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 31,
        name: "Aruba Gold",
        brand: "Emper",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 32,
        name: "Vulcan",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 4,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 33,
        name: "Vulcan Baie",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 34,
        name: "Very Berry Strawberry",
        brand: "Gelato",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 35,
        name: "Mango Tango",
        brand: "Gelato",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 36,
        name: "Viva la Vainilla",
        brand: "Gelato",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 37,
        name: "L'eau D'issey Pour Homme",
        brand: "Issey Miyake",
        ml: 125,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 38,
        name: "L'eau D'issey Pour Homme Sport",
        brand: "Issey Miyake",
        ml: 125,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 39,
        name: "Game of Spades Diamond",
        brand: "Jon Milano",
        ml: 90,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 40,
        name: "Game of Spades Esmerald",
        brand: "Jon Milano",
        ml: 90,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 41,
        name: "Game of Spades Royale",
        brand: "Jon Milano",
        ml: 90,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 42,
        name: "Atheeri",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 43,
        name: "Anssam",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 44,
        name: "Ameerat Al Arab",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 45,
        name: "Agham",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 46,
        name: "Ajwad",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 47,
        name: "Asad Clasico",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 48,
        name: "Asad Elixir",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 49,
        name: "Asad Bourbon",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 50,
        name: "Asad Edition Limited",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 51,
        name: "Eclaire",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 52,
        name: "Eclaire Pistache",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 53,
        name: "Eclaire Banofi",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 54,
        name: "Liam Grey",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 55,
        name: "Mayar Clasico",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 56,
        name: "Mayar Rosado",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 3,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 57,
        name: "Mayar Cherry Intense",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 58,
        name: "Liam Blue Shine",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 59,
        name: "Nebras Clasico",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 60,
        name: "Nebras Elixir",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 61,
        name: "Noble Blush",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 62,
        name: "The Kingdom Hombre",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 63,
        name: "The Kingdom Mujer",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 64,
        name: "Now",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 65,
        name: "Yara Elixir",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 66,
        name: "Yara Rosa",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 67,
        name: "Yara Moi",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 68,
        name: "Yara Tous",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 69,
        name: "Set de los 4 Yara",
        brand: "Lattafa",
        ml: 25, 
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 70,
        name: "Bright Peach",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 71,
        name: "Lovely Cherie",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 72,
        name: "Jean Lowe Azure",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 73,
        name: "Jean Lowe Inmortel",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 74,
        name: "Jean Lowe Vibe",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 1,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 75,
        name: "Salvo Intense",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 76,
        name: "Yeah Man",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 2,
        tags: [],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 77,
        name: "Amber Oud Gold Edition",
        brand: "Al Haramain",
        ml: 120,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 78,
        name: "Her",
        brand: "Burberry",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 79,
        name: "Light Blue",
        brand: "Dolce & Gabbana",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 80,
        name: "Light Blue",
        brand: "Dolce & Gabbana",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 81,
        name: "Infinite",
        brand: "Hugo Boss",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 82,
        name: "Boss 6",
        brand: "Hugo Boss",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 83,
        name: "L'eau D'issey Pour Homme",
        brand: "Issey Miyake",
        ml: 125,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 84,
        name: "Pisa",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 85,
        name: "Legend Spirit",
        brand: "Mont Blanc",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 86,
        name: "Toy Boy",
        brand: "Moschino",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 87,
        name: "Dylan Blue",
        brand: "Versace",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 88,
        name: "Set Badee Al Oud Honor And Glory 3 Pcs",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 89,
        name: "Set Thank U Next",
        brand: "Ariana Grande",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 90,
        name: "Set Cloud Pink",
        brand: "Ariana Grande",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 91,
        name: "One",
        brand: "Calvin Klein",
        ml: 200,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 92,
        name: "The Most Wanted Intense",
        brand: "Azzaro",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 93,
        name: "La Bomba",
        brand: "Carolina Herrera",
        ml: 80,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 94,
        name: "Veneno Scarlet",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 95,
        name: "Emporio Armani Stronger With You Intensely",
        brand: "Giorgio Armani",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 96,
        name: "Le Male Elixir",
        brand: "Jean Paul Gaultier",
        ml: 125,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 97,
        name: "Game Of Spades Wildcard",
        brand: "Jo Milano",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 98,
        name: "Eclaire",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 99,
        name: "One Million",
        brand: "Paco Rabanne",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 100,
        name: "Hawas Fire",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 101,
        name: "Hawas Kobra",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 102,
        name: "Uomo Born In Roma Intense",
        brand: "Valentino",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 103,
        name: "Eros",
        brand: "Versace",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 104,
        name: "Sceptre Desert",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 105,
        name: "Set Mini Polo",
        brand: "Ralph Lauren",
        ml: 60,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 106,
        name: "Set Discovery Stallion 53 The Black 92 Captcha 36 Ilang 62",
        brand: "Emper",
        ml: 30,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 107,
        name: "Hawas Tropical",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 108,
        name: "Art Of Universe",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 109,
        name: "9 Pm Rebel",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 110,
        name: "Set 9 Am Pour Femme",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 111,
        name: "9 Pm Elixir Parfum",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 112,
        name: "Odyssey Mandarin Sky",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 113,
        name: "Club de Nuit Urban Man Elixir",
        brand: "Armaf",
        ml: 105,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 114,
        name: "Odyssey Go Mango Topical",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 115,
        name: "Odyssey Mandarin Sky Vintage Edition",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 116,
        name: "Rome Pour Homme",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 117,
        name: "King",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 118,
        name: "Nitro Intense",
        brand: "Dumont",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 119,
        name: "Nitro Blue",
        brand: "Dumont",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 120,
        name: "Nitro Red Intensely",
        brand: "Dumont",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 121,
        name: "So Genius",
        brand: "Emper",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 122,
        name: "Game Of Spades All In",
        brand: "Jo Milano",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 123,
        name: "Purr",
        brand: "Katy Perry",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 124,
        name: "Meow",
        brand: "Katy Perry",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 125,
        name: "Yara Candy",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 126,
        name: "Khamrah Dukhan",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 127,
        name: "Badee Al Oud Amethyst",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 128,
        name: "Badee Al Oud Sublime",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 129,
        name: "Fakhar Gold Extrait",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 130,
        name: "His Confession",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 131,
        name: "Badee Al Oud Honor And Glory",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 132,
        name: "Yara Moi",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 133,
        name: "Khamrah",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 134,
        name: "Musaman White Intense",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 135,
        name: "Set Yara 2 Pcs",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 136,
        name: "Set Badee Al Oud Noble Blush 2 Pcs",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 137,
        name: "Sceptre Malachite",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 138,
        name: "Set Badee Al Oud Collection",
        brand: "Lattafa",
        ml: 5,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 139,
        name: "Club De Nuit Sillage",
        brand: "Armaf",
        ml: 105,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 140,
        name: "Club De Nuit Precieux 1 Extrait De Parfum",
        brand: "Armaf",
        ml: 55,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 141,
        name: "Odyssey Bahamas Tropical",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 142,
        name: "Nitro Red",
        brand: "Dumont",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 143,
        name: "Nitro White",
        brand: "Dumont",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 144,
        name: "Liquid Brun Avenue",
        brand: "Fragrance World",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 145,
        name: "Yara",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 146,
        name: "Angham",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 147,
        name: "Opulent Dubai",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 148,
        name: "New York The City of Dreams",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 149,
        name: "Reyna",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 150,
        name: "Jean Lowe Immortal",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 151,
        name: "Hawas Pink",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 152,
        name: "Hawas Atlantis",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 153,
        name: "9 Pm",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 154,
        name: "Set 9 Pm",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 155,
        name: "Odyssey Mandarin Sky",
        brand: "Armaf",
        ml: 200,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 156,
        name: "Odyssey Candee",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 157,
        name: "Odyssey Pink Pop",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 158,
        name: "Odyssey Lichi Lush",
        brand: "Armaf",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 159,
        name: "Rome",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 160,
        name: "Rome Paradoxe",
        brand: "Bharara",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 161,
        name: "Game Of Spades Full House",
        brand: "Jo Milano",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 162,
        name: "Hawas",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 163,
        name: "Hawas London",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 164,
        name: "Kismet",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 165,
        name: "Turathi Blue",
        brand: "Afnan",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 166,
        name: "Chaos",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 167,
        name: "Royal Blend Bourbon",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 168,
        name: "Royal Blend Sequoia",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 169,
        name: "Leau Dissey Pour Homme Intense",
        brand: "Issey Miyake",
        ml: 125,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 170,
        name: "Khamrah Qahwa",
        brand: "Lattafa",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 171,
        name: "Sweet Like Candy",
        brand: "Ariana Grande",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 172,
        name: "212 Vip Black Limited Edition",
        brand: "Carolina Herrera",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 173,
        name: "Vulcan Sable",
        brand: "Fragrance World",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 174,
        name: "Meringue",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 175,
        name: "Veneno Bianco",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 176,
        name: "Royal Blend Nero",
        brand: "French Avenue",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["unisex"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 177,
        name: "Montaigne Coco",
        brand: "Maison Alhambra",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 178,
        name: "Hawas Malibu",
        brand: "Rasasi",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["hombre"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 179,
        name: "Ciara",
        brand: "Revlon",
        ml: 68,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    },
    {
        id: 180,
        name: "Set Mandora 53",
        brand: "Emper",
        ml: 100,
        price: 0,
        discount: 0,
        stock: 0,
        tags: ["mujer"],
        image: "ruta-a-tu-imagen.jpg"
    }


]
